### ISSUE TITLE
Coverage report summary is 0 (NaN)

### ISSUE THREAD

**Issue by sw-tracker** [Teamop/merge-cobertura#1]
Hi there,
I am having the following issue when merging 2 reports.

Report 1:
```
<coverage timestamp="1710081180.524" line-rate="0.5541413373860182" branch-rate="0.21684134441633537"
          complexity="3751.0">
```

Report 2:
```
<coverage lines-valid="1107" lines-covered="792" line-rate="0.7154" branches-valid="634" branches-covered="369" branch-rate="0.5820000000000001" timestamp="1710101148073" complexity="0" version="0.1">
```

The merged report looks like this:
```
<coverage branch-rate="0" branches-covered="NaN" branches-valid="NaN" complexity="3751" line-rate="0"
          lines-covered="NaN" lines-valid="NaN" version="0.1" timestamp="1710102439602">
```

And if I print it with the `-p` options:
```
Total line Coverage: 0.00%
Total branch Coverage: 0.00%
Total average Coverage: 0.00%
```

I am using version `"merge-cobertura": "1.0.1"` and node `v18.18.2`

**Comment by Teamop** [comment]
thanks, will take a look when I'm available

**Comment by Teamop** [comment]
@sw-tracker I checked a little, found that it's caused by the Report 1 is not a valid Cobertura report. `NaN` was caused by the missing field in Report 1, but in Cobertura report, that's the required fields. So maybe you can check if your report is a valid one.
DTD - https://github.com/cobertura/web/blob/master/htdocs/xml/coverage-04.dtd

**Comment by sw-tracker** [comment]
@Teamop very strange, I generated that report using this:

```
code_coverage_backend:
  stage: release
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
  only:
    - main
    - merge_requests
  variables:
    JACOCO_AGGREGATE_FILEPATH: "my-app/target/site"
  script:
    # convert report from jacoco to cobertura
    - jacoco_paths=`find * -path "**/src/main/java" -type d | sed -e 's@^@'"$CI_PROJECT_DIR"'/@'`
    - python /opt/cover2cover.py $JACOCO_AGGREGATE_FILEPATH/jacoco-aggregate/jacoco.xml $jacoco_paths > $JACOCO_AGGREGATE_FILEPATH/backend-aggregate-cobertura.xml
  needs: ["release"]
  artifacts:
    paths:
      - $JACOCO_AGGREGATE_FILEPATH/backend-aggregate-cobertura.xml
```

It is the GitLab recommended way https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html#java-and-kotlin-examples
